# Generated by Django 5.0.3 on 2024-05-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('democrud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
